### ISSUE TITLE
resources.qrc generate file from pb_tool differs from Makefile

### ISSUE THREAD

**Issue by ThomasG77** [g-sherman/plugin_build_tool#1]
When I do `make compile` with a plugin generated from the "Plugin Builder", it generates a resources.py file from `resources.qrc` whereas doing a `pb_tool compile`, it generates a resources_rc.py.
Due to this when only using `pb_tool`, the generated plugin fails when loaded: it expects a resources.py because of `import resources`.
IMO,  we should unify the default behaviour.

**Comment by g-sherman** [comment]
Right---we changed the generation of the resources file because of issues caused by editing a .ui with Designer. pb_tool needs an update....

Thanks for pointing it out.

**Comment by g-sherman** [comment]
Version 1.9.1 fixes this issue;

pip install --upgrade pb-tool
