### ISSUE TITLE
pb_tool for QGIS 2.x

### ISSUE THREAD

**Issue by dortegat** [g-sherman/plugin_build_tool#10]
I try to install pb_tool for version 2.18.22 of QGIS (version of Python 2.7.14) by running: 
`python -m pip install pb_tool`

The installation is not completed:

_"  Found existing installation: Pygments 1.6
Cannot uninstall 'Pygments'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."_

Any ideas?

The development environment has been configured in the following way:

```
@echo off
SET QGIS_ROOT=C:\Program Files\QGIS 2.18
call "%QGIS_ROOT%"\bin\o4w_env.bat

@echo off
SET QGISNAME=qgis-ltr
path %PATH%;%QGIS_ROOT%\apps\%QGISNAME%\bin
path %PATH%;%QGIS_ROOT%\bin
path %PATH%;%QGIS_ROOT%\apps\Python27\Scripts

set PYTHONPATH=%PYTHONPATH%;%QGIS_ROOT%\apps\%QGISNAME%\python
set PYTHONHOME=%QGIS_ROOT%\apps\Python27

cmd.exe
```

**Comment by g-sherman** [comment]
Try:
`python -m pip install --ignore-installed Pygments`
